server {
    listen 80;
    server_name _;
    client_max_body_size 200m;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://slicer-api:8080;
        proxy_http_version 1.1;
        proxy_read_timeout 720s;
        proxy_send_timeout 720s;
        proxy_request_buffering off;
    }

    location / {
        try_files $uri /index.html;
    }
}
