export type HelpDiagram = 'nozzle' | 'layers' | 'first-layer' | 'width' | 'walls' | 'infill' | 'infill-density' | 'support-enable' | 'support-angle' | 'brim-type' | 'brim' | 'skirt' | 'raft' | 'z-hop' | 'motion' | 'rotation' | 'spiral' | 'top-layers' | 'bottom-layers' | 'printable-height' | 'z-offset';
export type SettingHelp = { text: string; diagram?: HelpDiagram };

export const settingHelp: Record<string, SettingHelp> = {
  nozzle_diameter: { text: 'Diameter of the physical nozzle opening. It constrains practical line widths and achievable detail.', diagram: 'nozzle' },
  nozzle_type: { text: 'Nozzle material affects wear resistance and suitable filament types. Abrasive composites usually need hardened steel.' },
  gcode_flavor: { text: 'Selects the command dialect expected by the printer firmware.' },
  printable_width: { text: 'Usable X-axis width of the build plate. This controls the preview bed and slicing boundary independently of the target-printer G-code preset.' },
  printable_depth: { text: 'Usable Y-axis depth of the build plate. This controls the preview bed and slicing boundary independently of the target-printer G-code preset.' },
  printable_height: { text: 'Maximum Z height the printer mechanism can reach and print.', diagram: 'printable-height' },
  z_offset: { text: 'Value added to every output G-code Z coordinate. Negative values move commanded Z closer to the bed; positive values move it farther away.', diagram: 'z-offset' },
  extruder_clearance_height_to_rod: { text: 'Distance from the nozzle tip to the lower toolhead rod. Orca uses it for collision checks in by-object printing.' },
  machine_max_speed_x: { text: 'Firmware maximum X-axis feed rate used for machine-limit output and time estimation, not normal print speed.' },
  machine_max_speed_y: { text: 'Firmware maximum Y-axis feed rate used for machine-limit output and time estimation, not normal print speed.' },
  machine_max_speed_z: { text: 'Firmware maximum Z-axis feed rate used for machine-limit output and time estimation, not normal print speed.' },
  machine_max_acceleration_extruding: { text: 'Maximum acceleration while extruding, corresponding to the printing acceleration limit such as M204 P.' },
  default_acceleration: { text: 'Default acceleration for normal printing and travel, except the initial layer, unless a feature-specific value overrides it.' },
  machine_start_gcode: { text: 'Commands inserted once at the start of the entire print.' },
  machine_end_gcode: { text: 'Commands inserted once at the end of the entire print.' },
  emit_machine_limits_to_gcode: { text: 'Writes configured machine limits into the G-code. Orca ignores this option for Klipper G-code flavor.' },
  silent_mode: { text: 'Declares a second lower-acceleration limit set for supported Marlin profiles and enables stealth-time estimation. It does not switch the printer into quiet mode.' },

  filament_type: { text: 'Material type assigned to this filament profile.' },
  filament_diameter: { text: 'Actual filament diameter used to convert requested plastic volume into extrusion length.' },
  filament_flow_ratio: { text: 'Multiplies every extrusion amount for this filament to compensate for measured over- or under-extrusion; Orca recommends calibration near 0.95–1.05.' },
  filament_max_volumetric_speed: { text: 'Maximum filament volume that may be melted and extruded per second. Orca limits print speed to stay below it; it cannot be zero.' },
  nozzle_temperature: { text: 'Nozzle temperature for every layer after the first.' },
  nozzle_temperature_initial_layer: { text: 'Nozzle temperature used while printing the first layer.' },
  hot_plate_temp: { text: 'High-temperature build-plate temperature after the first layer. Zero means this filament does not support that plate.' },
  hot_plate_temp_initial_layer: { text: 'High-temperature build-plate temperature for the first layer. Zero means this filament does not support that plate.' },
  fan_min_speed: { text: 'Lowest part-cooling fan speed used when cooling is active.' },
  fan_max_speed: { text: 'Maximum regular part-cooling fan speed to which automatic cooling may raise the fan.' },
  close_fan_the_first_x_layers: { text: 'Number of initial layers during which all cooling fans are turned off.' },
  full_fan_speed_layer: { text: 'Layer where the regular fan finishes its linear ramp to maximum. If not above the no-cooling layer count, maximum starts on the following layer.' },
  additional_cooling_fan_speed: { text: 'Auxiliary part-cooling fan speed after the no-cooling layers. The printer profile must enable the auxiliary fan.' },
  slow_down_layer_time: { text: 'Estimated layer times below this number of seconds trigger speed reduction for additional cooling.' },
  slow_down_for_layer_cooling: { text: 'Allows Orca to reduce print speed so short layers reach the configured maximum-fan layer-time threshold.' },
  enable_pressure_advance: { text: 'Uses this filament profile’s pressure/linear-advance value, overriding an automatic calibration result.' },
  pressure_advance: { text: 'Pressure Advance factor for Klipper, or Linear Advance factor for Marlin.' },
  filament_retraction_length: { text: 'Filament-specific override for the distance pulled back during retraction; zero disables retraction.' },
  filament_retraction_speed: { text: 'Filament-specific pullback speed. Filament restoration uses a separate de-retraction-speed setting.' },
  filament_retraction_minimum_travel: { text: 'Filament-specific travel-distance threshold; shorter travel moves do not retract.' },
  filament_retract_when_changing_layer: { text: 'Filament-specific override that retracts on layer changes. Spiral mode disables layer-change retraction.' },
  filament_shrink: { text: 'Measured XY size after cooling, as a percentage of the intended size—for example, enter 94% when 100 mm prints as 94 mm. Orca scales XY to compensate.' },
  temperature_vitrification: { text: 'Material softening temperature. If the bed is at or above it, Orca recommends opening the enclosure or removing the top glass to reduce clogging risk.' },
  filament_start_gcode: { text: 'Material-specific commands inserted when this filament begins printing.' },
  filament_end_gcode: { text: 'Material-specific commands inserted when this filament finishes printing.' },

  layer_height: { text: 'Height of each normal layer. Lower values improve vertical detail but increase print time.', diagram: 'layers' },
  initial_layer_print_height: { text: 'Height of the first layer. A thicker first layer can improve build-plate adhesion.', diagram: 'first-layer' },
  line_width: { text: 'Default extrusion width used when a feature-specific line width is zero. Percentage values are calculated from nozzle diameter.', diagram: 'width' },
  resolution: { text: 'Maximum contour simplification tolerance in millimeters. Lower values retain more points and create larger G-code; zero disables simplification.' },
  seam_position: { text: 'Controls the starting point of each outer wall, which determines where the visible seam appears.' },
  spiral_mode: { text: 'Continuously raises Z along the outer contour, turning a solid model into a seamless single-wall print with solid bottom layers.', diagram: 'spiral' },
  spiral_mode_smooth: { text: 'Smooths X/Y movement as well as Z during spiral printing, reducing abrupt direction changes on uneven vase contours.' },
  wall_loops: { text: 'Number of perimeter lines around the model. More loops increase wall strength and thickness.', diagram: 'walls' },
  wall_sequence: { text: 'Wall printing order. Inner/Outer favors overhang support; Inner/Outer/Inner favors finish and accuracy but requires at least three walls; Outer/Inner can make seams less consistent.' },
  wall_generator: { text: 'Arachne varies line width to fit thin features; Classic uses more uniform line widths.' },
  top_shell_layers: { text: 'Number of solid top-shell layers, including the visible top surface. Orca may add layers to satisfy a configured minimum top thickness.', diagram: 'top-layers' },
  bottom_shell_layers: { text: 'Number of solid bottom-shell layers, including the bottom surface. Orca may add layers to satisfy a configured minimum bottom thickness.', diagram: 'bottom-layers' },
  detect_thin_wall: { text: 'With the Classic wall generator, prints walls too narrow for two normal lines as one potentially open extrusion line.' },
  precise_outer_wall: { text: 'Adjusts outer-wall spacing to improve shell dimensions and layer consistency. Ignored for outer-inner and inner-outer-inner wall sequences.' },
  top_surface_pattern: { text: 'Line pattern used for visible top-surface solid infill.' },
  bottom_surface_pattern: { text: 'Line pattern used for bottom-surface solid infill; it does not control bridge infill.' },
  sparse_infill_density: { text: 'Percentage of internal sparse infill. At 100%, Orca converts it to solid infill and uses the internal solid-infill pattern.', diagram: 'infill-density' },
  sparse_infill_pattern: { text: 'Geometry used for sparse internal structure, affecting strength, speed, and material use.', diagram: 'infill' },
  infill_direction: { text: 'Base angle, in degrees, used to orient infill lines.' },
  initial_layer_speed: { text: 'Speed of first-layer paths except the solid-infill part of that layer.' },
  outer_wall_speed: { text: 'Speed of visible exterior perimeters; lower speeds generally improve surface quality.' },
  inner_wall_speed: { text: 'Speed of interior perimeters, which can often be faster than the outer wall.' },
  sparse_infill_speed: { text: 'Speed used for non-solid internal infill.' },
  internal_solid_infill_speed: { text: 'Speed used for fully solid internal regions.' },
  top_surface_speed: { text: 'Speed of the final visible top surface; lower values can improve finish.' },
  travel_speed: { text: 'Speed of non-extruding movements between printed regions.', diagram: 'motion' },
  bridge_speed: { text: 'Speed of externally visible bridge extrusions. In some overhang modes, Orca also uses it for walls with very little support.' },
  outer_wall_acceleration: { text: 'Acceleration used on visible outer walls; lower values can reduce ringing.' },
  bridge_acceleration: { text: 'Acceleration for bridges. A percentage is calculated from the outer-wall acceleration.' },
  enable_support: { text: 'Turns support generation on or off. When enabled, Orca adds removable material beneath regions selected by the support rules.', diagram: 'support-enable' },
  support_threshold_angle: { text: 'Generates automatic support where overhang slope is below this angle. Smaller values allow steeper unsupported slopes; zero uses overlap for normal support and 30° for tree support.', diagram: 'support-angle' },
  support_type: { text: 'Selects normal or tree support. Auto detects supported regions; manual generates only support enforcers you mark.' },
  support_style: { text: 'Selects support shape. Grid is stable; Snug reduces material and scarring; tree styles trade branch merging, strength, and large-flat-overhang structure.' },
  brim_type: { text: 'Selects where first-layer brim lines attach to the model: outside, inside holes, both, localized mouse ears, painted areas, automatic placement, or none.', diagram: 'brim-type' },
  brim_width: { text: 'Distance from the model to the outermost brim line.', diagram: 'brim' },
  skirt_loops: { text: 'Number of detached outline loops printed around the model to prime flow. Zero disables the skirt; a positive value enables that many loops.', diagram: 'skirt' },
  skirt_distance: { text: 'Distance from the skirt to the brim or, when there is no brim, to the model.', diagram: 'skirt' },
  raft_layers: { text: 'Raises the model by this number of support layers to form a raft. Zero disables the raft.', diagram: 'raft' },
  retraction_length: { text: 'Filament length pulled back to reduce ooze during long travel moves. A value of zero disables retraction.' },
  z_hop: { text: 'Vertical lift used during eligible retracted travel moves to reduce nozzle collisions with the print.', diagram: 'z-hop' },
  ironing_type: { text: 'Selects which surfaces receive a second same-height pass with a small flow to make them smoother.' },
  elefant_foot_compensation: { text: 'Shrinks the first layer in XY to compensate for outward bulging against the build plate.' },
  bridge_flow: { text: 'Bridge-flow ratio multiplied by filament flow and any object flow ratio. Values below 1 can reduce bridge sagging.' },
  fuzzy_skin: { text: 'Selects where random XY wall jitter is applied: painted regions, contour, holes, both, all walls, or disabled.' },
  fuzzy_skin_thickness: { text: 'Width of the random wall jitter used for fuzzy skin. Orca recommends keeping it below the outer-wall line width.' },
};

export const rangeHelp: Record<'min_z' | 'max_z', SettingHelp> = {
  min_z: { text: 'Lowest model Z height where this override range applies.' },
  max_z: { text: 'Highest model Z height where this override range applies.' },
};

export const transformHelp: Record<'positionX' | 'positionY' | 'rotationX' | 'rotationY' | 'rotationZ', SettingHelp> = {
  positionX: { text: 'Moves the selected model along the build plate’s X axis.' },
  positionY: { text: 'Moves the selected model along the build plate’s Y axis.' },
  rotationX: { text: 'Rotates the selected model around its X axis.', diagram: 'rotation' },
  rotationY: { text: 'Rotates the selected model around its Y axis.', diagram: 'rotation' },
  rotationZ: { text: 'Rotates the selected model around the vertical Z axis.', diagram: 'rotation' },
};
